### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MarkLaVenia**
Ch 5 & 6 (merged)

### CODE REVIEW

**Comment by tanho63** [comment]
Are you merging these into one week?

**Comment by ivelasq** [comment]
Yes! They will be merged into one week. I'll fix the dates for the following weeks.

**Comment by ivelasq** [comment]
@tanho63 please let me know if there are any issues!

**Comment by tanho63** [comment]
Got it!

**Review by tanho63 — APPROVED** [review]

**Pull request merged**
